const DisclaimerComponent = () => {
    return (
      <div className="max-w-4xl mx-auto p-8 bg-gradient-to-br from-white to-gray-50 rounded-xl shadow-lg border border-gray-100 transition-all duration-300 hover:shadow-xl">
        <div className="flex items-center mb-6 pb-4 border-b border-gray-200 mt-20">
          <div className="w-10 h-10 flex items-center justify-center bg-blue-500 text-white rounded-full mr-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path
                fillRule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                clipRule="evenodd"
              />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-gray-800">Disclaimer for Ticker Shorts</h2>
        </div>
  
        <div className="space-y-4 text-gray-700 leading-relaxed">
          <p className="text-base">
            The posts and articles on our platform reflect the personal opinions of the respective authors and may, on
            occasion, be generated by AI, which can occasionally produce inaccuracies. Such content does not necessarily
            represent the views of Ticker Shorts or any of its associates.
          </p>
  
          <p className="text-base">
            All information provided on our platform is for{" "}
            <span className="font-medium text-blue-700">informational and educational purposes only</span> and should not
            be construed as professional financial advice. If you require such advice, please consult a qualified
            financial or tax advisor.
          </p>
  
          <div className="bg-gray-50 p-4 rounded-lg border-l-4 border-blue-500 my-6">
            <p className="text-base font-medium text-gray-800">
              Investments in the securities market carry inherent risks, and you should review all related documents
              carefully before investing.
            </p>
          </div>
  
          <p className="text-base">
            The opinions, analysis, and commentary on our platform are subject to change without notice based on market
            conditions or other factors. Furthermore, any use of third-party websites or services linked on our platform
            is solely at your discretion and risk; Ticker Shorts is not responsible for the content, accuracy, or security
            of external sites.
          </p>
  
          <p className="text-base">
            Registration by SEBI, membership of BASL (in the case of Investment Advisors), and certification from NISM do
            not guarantee performance or assure returns.
          </p>
  
          <p className="text-base">
            Any examples or securities mentioned are provided for illustration purposes only and do not constitute a
            recommendation. Any reliance you place on such information is strictly at your own risk.
          </p>
  
          <p className="text-base">
            In no event shall Ticker Shorts be liable for any loss or damage, including without limitation indirect or
            consequential losses, or any loss arising from data loss or profit loss in connection with the use of this
            platform.
          </p>
        </div>
  
        <div className="mt-8 pt-4 border-t border-gray-200">
          <p className="font-medium text-gray-800 mb-4">
            By accessing our platform and its blog section, Newsletter or any other Services of Ticker Shorts you
            acknowledge and agree to our Terms and Conditions, Privacy Policy, and this Disclaimer.
          </p>
  
          <div className="flex flex-wrap gap-3">
            <button className="px-5 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors duration-300 flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fillRule="evenodd"
                  d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"
                  clipRule="evenodd"
                />
              </svg>
              Terms and Conditions
            </button>
            <button className="px-5 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors duration-300 flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fillRule="evenodd"
                  d="M18 8a6 6 0 01-7.743 5.743L10 14l-1 1-1 1H6v-1l1-1 1-1-1-1H6v-1h2l2.257-2.243A6 6 0 1118 8zm-6-4a1 1 0 100 2 2 2 0 012 2 1 1 0 102 0 4 4 0 00-4-4z"
                  clipRule="evenodd"
                />
              </svg>
              Privacy Policy
            </button>
          </div>
        </div>
      </div>
    )
  }
  
  export default DisclaimerComponent
  
  